### ISSUE TITLE
Color theme makes entire terminal 1 color

### ISSUE THREAD

**Issue by hahuang65** [arcticicestudio/nord-xresources#2]
There seems to be an issue where if I use the provided `.Xresources` file, sometimes the terminal will start completely in a pink color, with no visible cursor or letters when typing.

I've found that if I hard-code the color codes instead of using defined variables, this doesn't happen. Not sure how to reproduce as it's not consistent.

**Comment by arcticicestudio** [comment]
This sounds like a rendering problem of the terminal emulator or maybe even the running shell  🤔
The only color defined in Nord is `nord15`, but even this is not similar to pink.

It would be nice if you can take a screenshot/screencast next time this happens so we can get the exact color code. Also which terminal emulator and shell are you using? Maybe I'm able to reproduce it.

**Comment by hahuang65** [comment]
It's most definitely an issue of the terminal. I'm using urxvt, and I haven't been able to reproduce it since removing variable names. It works just fine with hard coded colors.

If you'd like, I can try to reproduce it by using variables again, but basically the window looks like a solid square of `#f990d6`, you can't see a cursor, and nothing happens if you type, like it's stuck before even getting to a user prompt, becomes completely unusable.

**Comment by sivakov512** [comment]
I have a similar problem with urxvt.

**Comment by arcticicestudio** [comment]
I hope the terminal developers fixed this problem in the meantime so I'll close this for now, otherwise it would be nice if you can post the link to the reported issue so I may track the status of it.
