### ISSUE TITLE
Why bright cyan has different color?

### ISSUE THREAD

**Issue by markand** [arcticicestudio/nord-xresources#4]
Hello,

It looks like all colors except black and white use the same value for both bold/non-bold colors. Except cyan.

Why do bright cyan has a different color? For instance, color14 is set to nord7 instead of nord8.

**Comment by arcticicestudio** [comment]
There is not other way to include almost all colors of Nord. The palette is limited to 16 colors only and using the same colors for the bright variations would completely exclude `nord7` next to `nord10`. If you'd like to have the same color for the normal and bright palette color you're free to modify the file to fit your needs, but I had to define the initial layout and decided to implement it the way it is now.
